const CatagoriesCardInfo = [
    {
    id:100,
    category:"Cups",
    name:"Refresh Rays",
    price:"₹899",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " The BrewMaster Mug boasts a robust build, featuring a sturdy handle that provides a secure and comfortable grip. Its generous capacity allows you (read more).",
    image :"https://static1.squarespace.com/static/5b608212ec4eb7a5e69c9cc6/5b61061270a6adeaf2a57443/614c8eb0b881202a0390d521/1638307021853/Minimalist-Unique-Designer-Coffee-Mug-Tea-Handmade-2.jpg?format=1500w"
    
},
{
    id:101,
    category:"Cups",
    name:"Zen Zips",
    price:"₹799",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " The BrewMaster Mug boasts a robust build, featuring a sturdy handle that provides a secure and comfortable grip. Its generous capacity allows you (read more).",
    image :"https://image.made-in-china.com/202f0j00FTDqlLAJCHpE/Irregular-Coffee-Mugs-Sets-Aesthetic-Cloud-Mugs-for-Tea-Coffee-Milk.jpg"
    
},
{
    id:102,
    category:"Cups",
    name:"Natures Edge",
    price:"₹759",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " The BrewMaster Mug boasts a robust build, featuring a sturdy handle that provides a secure and comfortable grip. Its generous capacity allows you (read more).",
    image :"https://res.cloudinary.com/dzdgpwtox/image/upload/w_750/u_designer-tool-uploads:bucket_4794:1615902431463.png,w_270,h_300,o_90,c_pad/u_radialize/fl_layer_apply,e_displace,y_-4/fl_layer_apply,x_20,y_-10/mugs/mockup1.jpg"
    
},
{
    id:103,
    category:"Cups",
    name:"Plutos",
    price:"₹789",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " The BrewMaster Mug boasts a robust build, featuring a sturdy handle that provides a secure and comfortable grip. Its generous capacity allows you (read more).",
    image :"https://rukminim1.flixcart.com/image/850/1000/kv1a4cw0/mug/8/v/u/ceramic-coffee-mug-400-1-nyrwana-delivering-smiles-in-inida-original-imag8fy4tqm9cf2s.jpeg?q=90"
    
},
{
    id:104,
    category:"Cups",
    name:"Heart's Ambush",
    price:"₹899",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " The BrewMaster Mug boasts a robust build, featuring a sturdy handle that provides a secure and comfortable grip. Its generous capacity allows you (read more).",
    image :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4MJzzl1kuX77S8_YDvCwpFoOpW3eWCyOlQxZx0RQddY2opL7ZS2W48trjJtWSHefqD1E&usqp=CAU"
    
},
{
    id:105,
    category:"Cups",
    name:"Drip up",
    price:"₹2399",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " The BrewMaster Mug boasts a robust build, featuring a sturdy handle that provides a secure and comfortable grip. Its generous capacity allows you (read more).",
    image :"https://favori.in/cdn/shop/files/20230504_0017.jpg?v=1683577739&width=1946"
    
},
{
    id:106,
    category:"Cups",
    name:"Minimal Tier",
    price:"₹799",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " The BrewMaster Mug boasts a robust build, featuring a sturdy handle that provides a secure and comfortable grip. Its generous capacity allows you (read more).",
    image :"https://img.tatacliq.com/images/i7/320Wx357H/MP000000009033393_320Wx357H_202103110244101.jpeg"
    
},
{
    id:107,
    category:"Dinnerware_Sets",
    name:"Celestial Dining",
    price:"₹6900",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " The BrewMaster Mug boasts a robust build, featuring a sturdy handle that provides a secure and comfortable grip. Its generous capacity allows you (read more).",
    image :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMzjnfY2W22-628cqnk1Xf2sU6SV0pCB0yWg&usqp=CAU"
    
},
{
    id:108,
    category:"Dinnerware_Sets",
    name:"Gourmet Gala Set",
    price:"₹6599",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " The BrewMaster Mug boasts a robust build, featuring a sturdy handle that provides a secure and comfortable grip. Its generous capacity allows you (read more).",
    image :"https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/A1j0D1DpkXL._AC_UF894,1000_QL80_.jpg"
    
},
{
    id:109,
    category:"Dinnerware_Sets",
    name:"Opulent Occasion Set",
    price:"₹8999",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " The BrewMaster Mug boasts a robust build, featuring a sturdy handle that provides a secure and comfortable grip. Its generous capacity allows you (read more).",
    image :"https://nestasia.in/cdn/shop/files/dinnerset_12.webp?v=1697030799"
    
},
{
    id:110,
    category:"Bowls",
    name:"Bountiful Bliss Bowl",
    price:"₹1209",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " Crafted with precision and care, this cup features a smooth, ergonomic design that fits perfectly in your hands, offering a cozy and snug feel with every sip (read more).",
    image :"https://nestasia.in/cdn/shop/products/DSC07334-2.jpg?v=1646733474"
    
},
{
    id:111,
    category:"Bowls",
    name:"SavorSphere Bowl",
    price:"₹1099",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " Crafted with precision and care, this cup features a smooth, ergonomic design that fits perfectly in your hands, offering a cozy and snug feel with every sip (read more).",
    image :"https://img.tatacliq.com/images/i9/320Wx357H/MP000000016353892_320Wx357H_202302031048511.jpeg"
    
},
{
    id:112,
    category:"Tea_Sets",
    name:"Graceful Gyokuro Set",
    price:"2799",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " Crafted with precision and care, this cup features a smooth, ergonomic design that fits perfectly in your hands, offering a cozy and snug feel with every sip (read more).",
    image :"https://djhiy8e1dslha.cloudfront.net/media/images/product/Medium/I00249625-1684751105.jpg"
    
},

{
    id:113,
    category:"Tea_Sets",
    name:"Artisanal Aromas Set",
    price:"₹2999",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " Crafted with precision and care, this cup features a smooth, ergonomic design that fits perfectly in your hands, offering a cozy and snug feel with every sip (read more).",
    image :"https://image.made-in-china.com/2f0j00uEtksYUJgdgC/Luxury-8PCS-Porcelain-Coffee-Tea-Set-with-Gold-Decor-Ceramic-Tea-Pot-and-Cup-Set.webp"
    
},
{
    id:114,
    category:"Tea_Sets",
    name:"Harmony Haven Set",
    price:"₹1899",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " Crafted with precision and care, this cup features a smooth, ergonomic design that fits perfectly in your hands, offering a cozy and snug feel with every sip (read more).",
    image :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7aDMpTRJbJgZw9f6l5Ese1QgDkJUzKAN4aw&usqp=CAU"
    
},
{
    id:115,
    category:"Limited_Edition",
    name:"Artisanal Accents Set",
    price:"₹4799",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " Crafted with precision and care, this cup features a smooth, ergonomic design that fits perfectly in your hands, offering a cozy and snug feel with every sip (read more).",
    image :"https://i.pinimg.com/736x/b5/96/df/b596dfa9eb2eb7b9bd75a6f734b21db3.jpg"
    
},
{
    id:116,
    category:"Limited_Edition",
    name:"Regency Reflections Set",
    price:"₹2099",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " Crafted with precision and care, this cup features a smooth, ergonomic design that fits perfectly in your hands, offering a cozy and snug feel with every sip (read more).",
    image :"https://angiehomes.co/cdn/shop/products/JIVEX-RED-_-GOLDEN-CUTLERY-ANGIE-KRIPALANI-DESIGN---ANGIE-HOMES-1620027316.jpg?v=1620027318"
    
},
{
    id:117,
    category:"Limited_Edition",
    name:"Monarch's Elixir Set",
    price:"₹7899",
    material:"Vitreous enamel",
    detaileddesc:"desc",
    quant:"2",
    offrnm1:"NEWONNEAT",
    offrnm2:"NoshPerk10",
    offrdtl2:"Get FLAT 10% OFF upto ₹200",
    offrdtl1:"Get FLAT 30% OFF upto ₹250 (only applicable for new customers)",
    delopt2:`Cash on delivery Available`,
    delopt1:`Express Delivery Available (Delivered in 3 Days)`,
    desc: " Crafted with precision and care, this cup features a smooth, ergonomic design that fits perfectly in your hands, offering a cozy and snug feel with every sip (read more).",
    image :"https://i.pinimg.com/originals/26/3e/ae/263eaeb9daea780a5f462fcb9493e1b9.jpg"
    
}


]

export default CatagoriesCardInfo;